---
title: "winloss"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{winloss}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, warning=FALSE}
library(prodlim)
library(winloss)
library(tidyverse)
library(magrittr)
```

# The HF-ACTION study

The HF-ACTION data comes from the WR package. We perform some initial data cleaning.

```{r}
library(WR)
data <- hfaction_cpx9

# Rename and recode id.
data$patid <- as.numeric(substr(data$patid, 6, 12))
names(data) <- c("id","time","status","group","age60")

# Time=0 problem (id==1359)
data <- data %>%
  mutate(time=ifelse(time<0.00001, 0.01, time)) 

# time=lag(time) problem (id=662).
data <- data %>%
  group_by(id) %>%
  mutate(time=ifelse(time==lag(time, default=0),time+0.001,time))

head(data)
```

Now we run the package command,

```{r}
fit <- winloss(id=data$id,
               time=data$time, 
               status=data$status, 
               group=data$group, 
               type=c(1,2), 
               at=47)
```

The fit contains 

* win-loss of each event type (wl) in the order win$_1$, loss$_1$, ect.
* 


and display the win-ratio with 95% confidence interval:

```{r}
c(fit$wr,fit$l_wr,fit$u_wr)
```
